name: cse-6242-project
channels:
  - defaults
dependencies:
  - pandas
  - numpy
  - scikit-learn
  - python=3.11
  - spotipy
  - seaborn
  - h5py
  - hdf5
  - jupyter
  - pytables
  - matplotlib
  - django
  - networkx