version: '3'

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - 'G:/My Drive/GT-Analytics/CSE-6242/Project/msd-metadata/:/root/db/'
